#################################
# Backend & Rendering
#################################

backend = "glx";
vsync = true;
use-damage = true;

#glx-no-stencil = true;
#glx-no-rebind-pixmap = true;
xrender-sync-fence = true;

#################################
# Opacità & Fading
#################################

fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 10;

inactive-opacity = 1.0;
active-opacity = 1.0;
frame-opacity = 1.0;

#################################
# Corners
#################################

corner-radius = 10;
rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'"
];

#################################
# Shadow (leggero)
#################################

shadow = true;
shadow-radius = 12;
shadow-opacity = 0.25;
shadow-offset-x = -7;
shadow-offset-y = -7;

shadow-exclude = [
  "name = 'Notification'",
  "class_g = 'dmenu'",
  "class_g = 'slop'",
  "window_type = 'dock'",
  "window_type = 'desktop'"
];

#################################
# Blur (DISATTIVATO per laptop Intel)
#################################

blur: {
  method = "dual_kawase";
  strength = 6; # Regola l'intensità (da 1 a 20)
  background = true;
  focus = false;
};

#################################
# Transparency rules
#################################

opacity-rule = [
  "95:class_g = 'st-256color' && focused",
  "70:class_g = 'st-256color' && !focused",
  "70:class_g = 'Thunar' && !focused",
  "95:class_g = 'Thunar' && focused",
  "70:class_g = 'librewolf' && !focused",
  "95:class_g = 'librewolf' && focused"
];

#################################
# Fix tearing Intel
#################################

unredir-if-possible = false;
detect-transient = true;
detect-client-leader = true;
vsync = true;

#################################
# Exclude
#################################

focus-exclude = [
  "class_g = 'slop'"
];

#################################
# Logging
#################################

log-level = "warn";

